In [2]:
import numpy as np

###创建数组

In [4]:
a = np.array([1, 2, 3]) #一维数组
a

array([1, 2, 3])

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]]) #二维数组
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
c = np.zeros((2, 3)) #创建一个2行3列的全零数组
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
d = np.ones((3, 4)) #创建一个3行4列的全一数组
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
e = np.full((2, 2), 7) #创建一个2行2列的全7数组
e

array([[7, 7],
       [7, 7]])

In [10]:
f = np.eye(3) #创建一个3x3的单位矩阵
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
g = np.random.rand(2, 3) #创建一个2行3列的随机数组
g

array([[0.05547966, 0.29775264, 0.50074506],
       [0.38649469, 0.86981595, 0.43819944]])

In [12]:
h = np.arange(0, 10, 2) #创建一个从0到10，步长为2的数组
h

array([0, 2, 4, 6, 8])

In [13]:
i = np.linspace(0, 1, 5) #创建一个从0到1，包含5个均匀分布的数的数组
i

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#种子本身的数值（0、1、2…）没有特别含义，只是决定起点。
#例如：
#你设 seed=0，永远得到那一串 [0.5488, 0.7151, …]
#你设 seed=1，永远得到另一串 [0.4170, 0.7203, …]
#换成 seed=2，又是另一串。

np.random.seed(0) #设置随机种子，确保每次生成的随机数相同   
k = np.random.randn(10) #创建一个包含10个标准正态分布随机数的一维数组
k

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [ ]:
np.random.rand(2,3) #创建一个2行3列的随机数组，满足[0,1) 均匀分布

array([[0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892]])

In [65]:
np.random.randn(2,3) #创建一个2行3列的标准正态分布随机数组

array([[-2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567]])

In [ ]:
np.random.randint(0, 10, (2, 3)) #整数随机，创建一个2行3列的随机整数数组，整数范围在0到10之间

array([[0, 4, 5],
       [5, 6, 8]])

### 数组属性

In [ ]:
a.shape #数组的形状

(3,)

In [15]:
b.shape #二维数组的形状

(2, 3)

In [16]:
a.dtype #数组的数据类型

dtype('int64')

In [17]:
c.dtype

dtype('float64')

In [19]:
a.ndim #数组的维度

1

In [20]:
b.ndim  #二维数组的维度

2

In [22]:
a.size #数组的元素个数

3

In [23]:
b.size #二维数组的元素个数

6

### 索引和切片

In [24]:
x = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
x [0] #第一行

array([10, 20, 30])

In [26]:
x[0,1] #第一行第二列

np.int64(20)

In [ ]:
x[:2] #前两行

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
x[1:] #第二行及之后的所有行

array([[40, 50, 60],
       [70, 80, 90]])

In [31]:
x[0:1,1:3] #第一行，第二列到第三列

array([[20, 30]])

In [32]:
x[x > 50] #所有大于50的元素

array([60, 70, 80, 90])

In [ ]:
x[[0, 2], [1, 2]] #第一行第二列和第三行第三列的元素, 第一个列表是行索引，第二个列表是列索引

array([20, 90])

In [35]:
x[[0, 0], [1, 2]]

array([20, 30])

### 数组运算

In [41]:
m = np.array([1, 2, 3])
n = np.array([4, 5, 6])

In [44]:
m + n #对应元素相加

array([5, 7, 9])

In [42]:
m - n #数组减法

array([-3, -3, -3])

In [43]:
m * n #对应元素相乘

array([ 4, 10, 18])

In [45]:
m / n #对应元素相除

array([0.25, 0.4 , 0.5 ])

In [47]:
m @ n #点积 1*4 + 2*5 + 3*6 = 32

np.int64(32)

In [48]:
m ** 2 #每个元素的平方

array([1, 4, 9])

In [49]:
np.sqrt(m) #每个元素的平方根

array([1.        , 1.41421356, 1.73205081])

### 统计

In [67]:
x = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [68]:
x.mean() #数组的均值

np.float64(50.0)

In [69]:
np.mean(x) #数组的均值

np.float64(50.0)

In [70]:
x.max() #数组的最大值

np.int64(90)

In [71]:
x.min() #数组的最小值

np.int64(10)

In [72]:
x.sum() #数组元素的和

np.int64(450)

In [ ]:
x.median() #数组的中位数 (错误，AttributeError: 'numpy.ndarray' object has no attribute 'median')

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [74]:
np.median(x) #数组的中位数

np.float64(50.0)

In [76]:
np.std(x) #数组的标准差

np.float64(25.81988897471611)

### 矩阵运算

In [77]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [78]:
B = np.array([[5, 6], [7, 8]])
B

array([[5, 6],
       [7, 8]])

In [ ]:
A @ B #矩阵乘法, A的列数必须等于B的行数,1*5+2*7=19, 1*6+2*8=22; 1*5+4*7=43, 1*6+4*8=50

array([[19, 22],
       [43, 50]])

In [80]:
A * B #对应元素相乘

array([[ 5, 12],
       [21, 32]])

In [81]:
np.dot(A, B) #矩阵乘法, 等同于 A @ B

array([[19, 22],
       [43, 50]])

In [ ]:
# 如果 A 是布尔类型（dtype=bool），np.invert(A) 就是 逻辑取反（等价于 np.logical_not(A) 或 ~A）。
# 如果 A 是整数类型（int），np.invert(A) 就是 按位取反（bitwise NOT），等价于 ~A。
# 如果 A 是浮点数，NumPy 会报错，因为浮点数没有定义按位取反。
np.invert(A) #矩阵求逆, A必须是方阵且行列式不为0 ,解释：~n = -(n+1)

array([[-2, -3],
       [-4, -5]])

### 广播机制（Broadcasting）

In [9]:
# 标量与数组运算
a = np.array([1,2,3])
b = 10
c = a + b #广播机制, b会自动扩展为与a相同的形状，即[10,10,10]
a, b, c

(array([1, 2, 3]), 10, array([11, 12, 13]))

In [ ]:
# 二维数组与一维数组运算
M = np.array([[1,2,3],
              [4,5,6]])
v = np.array([10,20,30])
result = M + v #广播机制，v会自动扩展为与M相同的形状，即[[10,20,30],[10,20,30]]
M, v, result

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([10, 20, 30]),
 array([[11, 22, 33],
        [14, 25, 36]]))

In [7]:
# 不同维度广播
A = np.ones((3,1))
B = np.array([1,2,3])
C = A + B #A会扩展为[[1,1,1],[1,1,1],[1,1,1]], B会扩展为[[1,2,3],[1,2,3],[1,2,3]]
A, B, C

(array([[1.],
        [1.],
        [1.]]),
 array([1, 2, 3]),
 array([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]]))