In [16]:
import numpy as np

In [17]:
# 生成一个 5x5 的单位矩阵
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# 创建一个 1 到 100 的数组，并取偶数
b = np.arange(0,101,2)
b

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
b[[1,3,5]]  # 取索引为1,3,5的元素

array([ 2,  6, 10])

In [19]:
# 创建一个 1 到 100 的数组，并求所有偶数之和
c = np.arange(1,101)
even = c[c%2==0]
sum = np.sum(even)
sum

np.int64(2550)

In [20]:
# 对一个二维数组按列求和
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
col_sum = np.sum(d, axis=0)
col_sum

array([12, 15, 18])

In [21]:
# 求一个矩阵的逆矩阵、行列式和特征值
e = np.array([[1,2],[3,4]])
inv_e = np.linalg.inv(e)
det_e = np.linalg.det(e)
eigvals_e = np.linalg.eigvals(e)
inv_e, det_e, eigvals_e

(array([[-2. ,  1. ],
        [ 1.5, -0.5]]),
 np.float64(-2.0000000000000004),
 array([-0.37228132,  5.37228132]))

In [23]:
# 普通 Python 循环 vs 向量化

# 普通 Python 循环
a = [1,2,3,4,5]
b = [10,20,30,40,50]
c = []
for i in range(len(a)):
    c.append(a[i] + b[i])
print("普通循环:", c)

# NumPy 向量化运算
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
c = arr1 + arr2
print("向量化运算:", c)

普通循环: [11, 22, 33, 44, 55]
向量化运算: [11 22 33 44 55]


In [24]:
# 平方运算

# 普通循环
nums = [1,2,3,4,5]
squares = [x**2 for x in nums]
print("普通循环:", squares)

# 向量化
arr = np.array([1,2,3,4,5])
squares = arr**2
print("向量化运算:", squares)


普通循环: [1, 4, 9, 16, 25]
向量化运算: [ 1  4  9 16 25]
